name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: read
  # pages: write
  # id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false



jobs:
  release:

    defaults:
      run:
        shell: nix develop --command bash {0}
        
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"